### ISSUE TITLE
Switch wordlists config to string instead of list

### ISSUE THREAD

**Issue by ocervell** [glitchedgitz/cook#46]
```yml
files:
  bo0m_fuzz: [https://raw.githubusercontent.com/Bo0oM/fuzz.txt/master/fuzz.txt]
raw_files:
  bxss: [E:\tools\base\bxss.txt]
```

Is there a reason why the value of the wordlist is a list here ?

Should we maybe switch to:
```yml
files:
  bo0m_fuzz: "https://raw.githubusercontent.com/Bo0oM/fuzz.txt/master/fuzz.txt"
raw_files:
  bxss: "E:\tools\base\bxss.txt"
```

**Comment by glitchedgitz** [comment]
It is list because it can combine the wordlists from the multiple urls.   

![image](https://github.com/glitchedgitz/cook/assets/58145476/b420784c-7e74-40c2-a680-c66dc6c0c39f)


Let's say you found multiple good wordlist for a particular thing let say `api`
```yaml
files: 
     my-api:
         - URL 1
         - URL 2
         - URL 3
         ....
         - URL n
```
Now when you call `my-api` It will combine them.
